DROP TABLE IF EXISTS TREATMENT_PLAN;
DROP TABLE IF EXISTS TREATMENT_TASK;

CREATE TABLE TREATMENT_PLAN (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_reference VARCHAR(255) NOT NULL,
    treatment_action VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    recurrence_pattern VARCHAR(255)
);

CREATE TABLE TREATMENT_TASK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_reference VARCHAR(255) NOT NULL,
    treatment_action VARCHAR(255) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
);
